# _config.yml
# Setup
title: aibOS
description: 'Notion 블로그'
url: https://biainthew.github.io
baseurl: ""

# About/contact
author:
  name: 이비아
  url: https://github.com/biainthew
  email: lba0507@gmail.com

# Pagination
#paginate: 5
#paginate_path: '/page:num/'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

# Markdown
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Hyde specific settings
sidebar_home_link: true
sidebar_blog_link: '/archive/'

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/biainthew/aibOS

# Exclude
exclude:
  - node_modules/
  - scripts/
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - .github/
  - README.md